### ISSUE TITLE
同时拖拽多个node到group中

### ISSUE THREAD

**Issue by wxy1995** [alibaba/GGEditor#268]
## 这个功能解决了什么问题

单个node可以被拖拽进group中：
![image](https://user-images.githubusercontent.com/11352010/59009528-9a641900-8860-11e9-80b3-dab5b2512bec.png)
 
希望能够有批量操作，多个被选中的node也能被拖拽进group，目前是不支持的：
![image](https://user-images.githubusercontent.com/11352010/59009588-c8495d80-8860-11e9-913a-66da537b3898.png)

## 你所期望的 API 是怎样的
暂无

**Comment by ShirlyZhang** [comment]
可以贴个代码借我参考一下吗，在做这个部分，万分感谢
