### ISSUE TITLE
不能从node连线到group，只能从group连线到node

### ISSUE THREAD

**Issue by zibu15** [alibaba/GGEditor#371]
## 期望的结果是什么
可以从node连接到group
## 实际的结果是什么
只能从group连接到node

**Comment by xiaoxiaorose** [comment]
在拖布处，如何实现单项连线，也就是不形成闭环线

**Comment by dbFlower** [comment]
format了一下 `gg-editor-core` 的 bundle， 找到了控制显示锚点的代码
![image](https://user-images.githubusercontent.com/9190813/66696924-04a33380-ed03-11e9-965e-2c8bac724bf4.png)
发现原因是划线部分只调用了获取所有节点，所以通过覆盖该方法的方式实现了
```js
function clone(source) {
  return Object.assign(Object.create(Object.getPrototypeOf(source)), source);
}

/**
 * https://github.com/alibaba/GGEditor/issues/371
 * @override 覆盖当前页面默认的 dragEdgeBeforeShowAnchor, 节点也可以连接组了
 * @param {*} page 当前页面
 */
export function overrideDragEdgeBeforeShowAnchor(page) {
  const handler = page.dragEdgeBeforeShowAnchor;
  const nodeHandler = handler.bind(page);
  const clonePage = clone(page);

  clonePage.getGraph = () => {
    const graph = page.getGraph();
    return {
      getNodes() {
        const groups = graph.getGroups();
        return groups;
      },
    };
  };

  const groupHandler = handler.bind(clonePage);

  page.dragEdgeBeforeShowAnchor = function (...args) {
    nodeHandler(...args);
    groupHandler(...args);
  };
}
```

```jsx
import { withPropsAPI } from 'gg-editor'

const Comp = (props) => {
  // 刚加载的时候是拿不到page的
  setTimeout(() => {
    const page = props.propsAPI.editor.getCurrentPage();
    console.log('current page', page);
    if (page) {
      overrideDragEdgeBeforeShowAnchor(page);
    }
  });
  return null
}

export default withPropsAPI(Comp)
```

**Comment by zibu15** [comment]
> format了一下 `gg-editor-core` 的 bundle， 找到了控制显示锚点的代码
> ![image](https://user-images.githubusercontent.com/9190813/66696924-04a33380-ed03-11e9-965e-2c8bac724bf4.png)
> 发现原因是划线部分只调用了获取所有节点，所以通过覆盖该方法的方式实现了
> 
> ```js
> function clone(source) {
>   return Object.assign(Object.create(Object.getPrototypeOf(source)), source);
> }
> 
> /**
>  * https://github.com/alibaba/GGEditor/issues/371
>  * @override 覆盖当前页面默认的 dragEdgeBeforeShowAnchor, 节点也可以连接组了
>  * @param {*} page 当前页面
>  */
> export function overrideDragEdgeBeforeShowAnchor(page) {
>   const handler = page.dragEdgeBeforeShowAnchor;
>   const nodeHandler = handler.bind(page);
>   const clonePage = clone(page);
> 
>   clonePage.getGraph = () => {
>     const graph = page.getGraph();
>     return {
>       getNodes() {
>         const groups = graph.getGroups();
>         return groups;
>       },
>     };
>   };
> 
>   const groupHandler = handler.bind(clonePage);
> 
>   page.dragEdgeBeforeShowAnchor = function (...args) {
>     // 如果是 group 的话，先将 group 克隆一份然后将 group.isNode 设为 true
>     let source = sourceNode;
>     if (source.type === 'group') {
>       source = Object.assign(clone(sourceNode), { isNode: true });
>     }
> 
>     nodeHandler(source, ...extra);
>     groupHandler(source, ...extra);
>   };
> }
> ```
> 
> ```js-jsx
> import { withPropsAPI } from 'gg-editor'
> 
> const Comp = (props) => {
>   // 刚加载的时候是拿不到page的
>   setTimeout(() => {
>     const page = props.propsAPI.editor.getCurrentPage();
>     console.log('current page', page);
>     if (page) {
>       overrideDragEdgeBeforeShowAnchor(page);
>     }
>   });
>   return null
> }
> 
> export default withPropsAPI(Comp)
> ```

**Comment by zxgjwy0216** [comment]
> format了一下 `gg-editor-core` 的 bundle， 找到了控制显示锚点的代码
> ![image](https://user-images.githubusercontent.com/9190813/66696924-04a33380-ed03-11e9-965e-2c8bac724bf4.png)
> 发现原因是划线部分只调用了获取所有节点，所以通过覆盖该方法的方式实现了
> 
> ```js
> function clone(source) {
>   return Object.assign(Object.create(Object.getPrototypeOf(source)), source);
> }
> 
> /**
>  * https://github.com/alibaba/GGEditor/issues/371
>  * @override 覆盖当前页面默认的 dragEdgeBeforeShowAnchor, 节点也可以连接组了
>  * @param {*} page 当前页面
>  */
> export function overrideDragEdgeBeforeShowAnchor(page) {
>   const handler = page.dragEdgeBeforeShowAnchor;
>   const nodeHandler = handler.bind(page);
>   const clonePage = clone(page);
> 
>   clonePage.getGraph = () => {
>     const graph = page.getGraph();
>     return {
>       getNodes() {
>         const groups = graph.getGroups();
>         return groups;
>       },
>     };
>   };
> 
>   const groupHandler = handler.bind(clonePage);
> 
>   page.dragEdgeBeforeShowAnchor = function (...args) {
>     // 如果是 group 的话，先将 group 克隆一份然后将 group.isNode 设为 true
>     let source = sourceNode;
>     if (source.type === 'group') {
>       source = Object.assign(clone(sourceNode), { isNode: true });
>     }
> 
>     nodeHandler(source, ...extra);
>     groupHandler(source, ...extra);
>   };
> }
> ```
> 
> ```js-jsx
> import { withPropsAPI } from 'gg-editor'
> 
> const Comp = (props) => {
>   // 刚加载的时候是拿不到page的
>   setTimeout(() => {
>     const page = props.propsAPI.editor.getCurrentPage();
>     console.log('current page', page);
>     if (page) {
>       overrideDragEdgeBeforeShowAnchor(page);
>     }
>   });
>   return null
> }
> 
> export default withPropsAPI(Comp)
> ```

你好，我想问一下，我应该把这个替换文件放在哪个地方呢
