### ISSUE TITLE
这种节点样式是怎么配出来的，求高力大佬给份代码

### ISSUE THREAD

**Issue by mxy2316868975javascript** [alibaba/GGEditor#398]
## 你所期望的 API 是怎样的

![image](https://user-images.githubusercontent.com/15233384/68278829-21861900-00ad-11ea-840a-4b44c2271d0a.png)

@gaoli

**Comment by Aragornzero** [comment]
有相关的代码的，自己翻翻吧。我看了几次了

**Comment by smlHao** [comment]
@Aragornzero  在哪看的代码？

**Comment by Aragornzero** [comment]
#76

**Comment by smlHao** [comment]
@Aragornzero   大神啊   再请教下 CanvasPanel里里定义了一个 怎样在propsAPI.save()里获取到在输入的值？

**Comment by Aragornzero** [comment]
> @Aragornzero 大神啊 再请教下 CanvasPanel里里定义了一个 怎样在propsAPI.save()里获取到在输入的值？

不是很明白你的意思. 如果是定义了节点,没有数据的话也是不会显示对应的图案的. 输入数据有两种方式,一种是拖动、一种是直接data传入. 如果你是问propsAPI怎么用,那又是另外一回事了.

**Comment by smlHao** [comment]
@Aragornzero   CanvasPanel里里定义了一个Input 输入框 ，又定义了一个保存的ToorButton，在点击保存的时候propsAPI.save()只有nodes和edges ，怎么获取到输入框的值呢？

**Comment by Aragornzero** [comment]
> @Aragornzero CanvasPanel里里定义了一个Input 输入框 ，又定义了一个保存的ToorButton，在点击保存的时候propsAPI.save()只有nodes和edges ，怎么获取到输入框的值呢？

你的描述很不清晰啊。我查看代码，也没有CanvasPanel这个组件。但是根据你的描述，有可能是DetailPanel，单击节点后，右边暂时相关的属性，所有有个input。但只有input不代表就修改了data里面的数据，估计你需要搭配propsAPI中的update来更新数据，然后你再执行save方法，数据才会改变。

**Comment by smlHao** [comment]
![image](https://user-images.githubusercontent.com/3837738/68355825-76786c80-014b-11ea-8dc7-78d6793ef00f.png)

![image](https://user-images.githubusercontent.com/3837738/68355886-afb0dc80-014b-11ea-9936-d5cc10bf64c3.png)

![image](https://user-images.githubusercontent.com/3837738/68355971-eb4ba680-014b-11ea-9625-9609f402bf2d.png)

@Aragornzero  不是点击节点  是点击空白处会显示CanvasPanel里的组件FlowDetail ，FlowDetail组件里定义了一个Input ，我想在点击"保存"的时候获取到Input里输入的值，应该怎么弄呢？

**Comment by Aragornzero** [comment]
> ![image](https://user-images.githubusercontent.com/3837738/68355825-76786c80-014b-11ea-8dc7-78d6793ef00f.png)
> 
> ![image](https://user-images.githubusercontent.com/3837738/68355886-afb0dc80-014b-11ea-9936-d5cc10bf64c3.png)
> 
> ![image](https://user-images.githubusercontent.com/3837738/68355971-eb4ba680-014b-11ea-9625-9609f402bf2d.png)
> 
> @Aragornzero 不是点击节点 是点击空白处会显示CanvasPanel里的组件FlowDetail ，FlowDetail组件里定义了一个Input ，我想在点击"保存"的时候获取到Input里输入的值，应该怎么弄呢？

其实是一样的道理，你写个函数，在canvasPanel中的input变化后执行，先用save()读取全部数据，然后把input中的值保存在数据里面，然后在用reac()把数据读回去，这样你在用save()时就会有input的数据了啦。只不过这个不是节点数据，它不会展示而已。

**Comment by smlHao** [comment]
![image](https://user-images.githubusercontent.com/3837738/68357088-31563980-014f-11ea-9e57-5b0527c9aeb4.png)

![image](https://user-images.githubusercontent.com/3837738/68357114-4501a000-014f-11ea-859b-d024e0824cce.png)

@Aragornzero  这样做save还是取不到值，是我写的有问题吗？

**Comment by Aragornzero** [comment]
> @Aragornzero 这样做save还是取不到值，是我写的有问题吗？

这样啊，我没有这样的需求，所以具体尝试过。或许read的时候，它过滤的一下，只读nodes和edges。你试试看吧，实在不行就当做一个节点id保存进去，不要添加shape等数据，不渲染出来也行。

**Comment by smlHao** [comment]
@Aragornzero  好的  多谢了

**Comment by mxy2316868975javascript** [comment]
![image](https://user-images.githubusercontent.com/15233384/68744399-7edf1480-062f-11ea-8185-033dfa1978d0.png)
这个省略号是怎么造成的

**Comment by mxy2316868975javascript** [comment]
> > @Aragornzero 这样做save还是取不到值，是我写的有问题吗？
> 
> 这样啊，我没有这样的需求，所以具体尝试过。或许read的时候，它过滤的一下，只读nodes和edges。你试试看吧，实在不行就当做一个节点id保存进去，不要添加shape等数据，不渲染出来也行。

**Comment by mxy2316868975javascript** [comment]
> 有相关的代码的，自己翻翻吧。我看了几次了

给个联系方式吧
