### ISSUE TITLE
graph 是否有加载/绘制完成的事件

### ISSUE THREAD

**Issue by xzhyj93** [alibaba/GGEditor#402]
请问 graph 是否有加载完成的事件呢？类似 onLoad。希望在 graph 加载完成后进行一些操作，如更新数据等

**Comment by xzhyj93** [comment]
我最后解决方法是监听 onAfterChange 事件，判断 e.action === 'changeData' 时执行操作

**Comment by Anonlyy** [comment]
@xzhyj93 老哥,为什么我的 加载完成后不会触发 onAfterChange
