### ISSUE TITLE
2.0.4版本如何获取到graph对象

### ISSUE THREAD

**Issue by WangJM001** [alibaba/GGEditor#408]
请问2.0.4版本如何获取到graph对象？
需要调用toDataUrl方法

**Comment by BigYu** [comment]
通过ref可以拿到

```const { graph } = yourGGEditorComponentRef.current;```

**Comment by WangJM001** [comment]
没有current属性啊，是在哪个组件上ref，GGEditor?还是子组件Mind?
![image](https://user-images.githubusercontent.com/20501316/69018791-e78c0f80-09e8-11ea-8f61-2d2af1b370e2.png)

**Comment by BigYu** [comment]
> 没有current属性啊，是在哪个组件上ref，GGEditor?还是子组件Mind?
> ![image](https://user-images.githubusercontent.com/20501316/69018791-e78c0f80-09e8-11ea-8f61-2d2af1b370e2.png)

应该是在<Flow />的refs上能拿到。
至于current，我代码里用的[createRef](https://reactjs.org/docs/react-api.html#reactcreateref) 如果是直接拿ref的话就没有，不用在意这种细节哈哈。

**Comment by WangJM001** [comment]
感谢，先实现功能吧，3.0应该也快了

**Comment by WangJM001** [comment]
好像不是原生的graph对象，没有toDataUrl属性

**Comment by Anonlyy** [comment]
@WangJM001 你好解决了吗,老哥

**Comment by WangJM001** [comment]
我项目的需求是搞定了，后来换成g6-editor了，也已经不维护了，你现在是什么问题，我看看能不能帮助到你

**Comment by Anonlyy** [comment]
一样的功能, 就是想要调用 downloadImage()、toDataUrl() 实现下载功能,谢谢老哥

**Comment by WangJM001** [comment]
这些是g6 3.0的api，2.0.4版本用的是g6 2.0+

**Comment by Anonlyy** [comment]
所以适合不支持是吗?

**Comment by WangJM001** [comment]
const image =page.saveExpandImage()  // mind
const image =page.saveImage(); // flow
const base64ImgData = image.toDataURL('image/png');

**Comment by WangJM001** [comment]
你试试吧，不确定有没有，因为我后来换g6editor了，感觉这个版本有一些bug、g6editor好用些

**Comment by WangJM001** [comment]
你可以把editor对象打印出来看看，文档都没写，里面应该有相应的方法，上面的方法就是我在g6editor里找到的
gg-editor-core应该类似g6editor

**Comment by Anonlyy** [comment]
好的谢谢老哥我试试

**Comment by WangJM001** [comment]
忘了贴了
const page = editor.getCurrentPage();

**Comment by Anonlyy** [comment]
太棒了,谢谢老哥,可以了哈哈

**Comment by tombsmrliu** [comment]
赞一个 我还以为我那个功能没希望了。对了我在额外引入g6库项目不能运行你们遇到过吗？
