### ISSUE TITLE
flow是否可以提供激活某个节点的接口方法

### ISSUE THREAD

**Issue by fshipei** [alibaba/GGEditor#424]

**Comment by zedwang** [comment]
已经解决了吗？@fshipei

**Comment by sd445419855** [comment]
@fshipei 遇到了同样的问题，请问现在解决了吗？

**Comment by zibu15** [comment]
同关注

**Comment by gaoli** [comment]
@fshipei 这个方法应该能解决你的问题：

https://github.com/alibaba/GGEditor/blob/master/src/utils/index.ts#L105

**Comment by sd445419855** [comment]
非常感谢，我试试看



445419855@qq.com
 
Sender: 高力
Send Time: 2020-04-13 11:26
Receiver: alibaba/GGEditor
cc: sd445419855; Comment
Subject: Re: [alibaba/GGEditor] flow是否可以提供激活某个节点的接口方法 (#424)
@fshipei 这个方法应该能解决你的问题：
https://github.com/alibaba/GGEditor/blob/master/src/utils/index.ts#L105

**Comment by zxgjwy0216** [comment]
可是 setItemState 这个API 是3.0的，哎。
