### ISSUE TITLE
锚点自定义

### ISSUE THREAD

**Issue by wlds** [alibaba/GGEditor#426]
2.0.4版本的 demo，拖拽的node 可以自定义其锚点吗？
![image](https://user-images.githubusercontent.com/26653083/70311169-10ffc480-184c-11ea-9fcc-6f612ab44aef.png)

**Comment by wlds** [comment]
解决了。。。

**Comment by JoMartinezZhu** [comment]
> 解决了。。。

方便在 codesandbox 给出demo嘛

**Comment by wlds** [comment]
@JoMartinezZhu  可以参考 #150
