### ISSUE TITLE
新版本使用withEditorContext不能使用保存功能

### ISSUE THREAD

**Issue by cocoboy84520** [alibaba/GGEditor#468]
## 你所期望的 API 是怎样的
import GGEditor, { Flow,EditableLabel, Item, ItemPanel,withEditorContext } from 'gg-editor';
class flowdesign extends Component {
.....
}
export default withEditorContext(flowdesign)

代码如上，页面渲染空白

**Comment by zhy1516** [comment]
同样的问题，gaoli 大神能出来指点指点吗
