### ISSUE TITLE
自定义节点拖拽到画布时而出现异常

### ISSUE THREAD

**Issue by pkc-yiller** [alibaba/GGEditor#480]
## 版本

> 3.0.6

## 环境

> windows7、google

异常信息：
TypeError: Cannot read property 'getBBox' of null
e.handleMouseMove
node_modules/_gg-editor@3.0.6@gg-editor/es/index.js:2997

**Comment by gaoli** [comment]
@pkc-yiller 能提供一个简单的 DEMO 吗？

**Comment by pkc-yiller** [comment]
https://codesandbox.io/s/long-dream-xlbq3?file=/src/index.js
拖拽多次节点放入画布中，在画布移动节点，就能重现异常

**Comment by gaoli** [comment]
@pkc-yiller 升级到 3.1.0 版本，应该能解决你的问题：）

**Comment by pkc-yiller** [comment]
好的，感谢Thanks♪(･ω･)ﾉ

**Comment by pkc-yiller** [comment]
@gaoli 请问一下，3.1.0版本有提供registerGroup 效果嘛.

**Comment by gaoli** [comment]
@pkc-yiller 3.1.0 版还没有，后继版本会加上：）
