### ISSUE TITLE
node和edge的右键菜单没有了

### ISSUE THREAD

**Issue by KelleyYe** [alibaba/GGEditor#485]
## 版本

> 3.1.0

## 期望的结果是什么
> 2.X中的EdgeMenu和NodeMenu

## 实际的结果是什么
> 最新版中没有了EdgeMenu和NodeMenu右键菜单

**Comment by gaoli** [comment]
@KelleyYe 可以参照这个 [Demo](https://github.com/alibaba/GGEditor/blob/master/examples/plugin-item-popover/index.tsx)

**Comment by KelleyYe** [comment]
@gaoli 谢谢，找到了！你回复的太迅速了！👍

**Comment by zlyyyy** [comment]
@gaoli 链接404，可以再发下嘛

**Comment by iwits** [comment]
@gaoli 链接404，可以再发下嘛
