### ISSUE TITLE
自定义节点，颜色

### ISSUE THREAD

**Issue by eevin** [alibaba/GGEditor#494]
1、注册节点
<RegisterNode
      name="customStart"
      ....
      extend="circle"
    />

使用getCustomConfig 设置颜色无效，始终显示默认”蓝色“，仅能在
<ItemPanel>
    <Item
      model={{
        type: 'customStart',
        label: '开始',
        size: 72,
        color: 'red',
      }}
    >
      <img src={start} alt="" draggable={false} />
    </Item>
</ItemPanel>
设置color 能改变边框颜色。

1、如何配置：circle，rect，diamond等形状的内容，文字颜色。
2、选中节点颜色加深如何实现？

**Comment by gaoli** [comment]
@eevin 试试这个在线 [Demo](https://ggeditor.com/examples/register/node) :)

**Comment by eevin** [comment]
@gaoli 
明白了，十分感谢！
还有个疑问，使用RegisterNode 自定义了一个节点，那么在ItemPanel里面是不是要制作一张和自定义节点一样的图片。

**Comment by eevin** [comment]
@gaoli 
demo中还是一样的问题，只有extend="bizFlowNode" 才能设置颜色
其他形状，circle，rect，diamond 如何处理。

**Comment by gaoli** [comment]
@eevin 内置的节点属性 g6 直接提供，可以参照这个 [文档](https://www.yuque.com/antv/g6/internal-node) :)

**Comment by eevin** [comment]
@gaoli 我也看到文档了，按照文档上面配置getCustomConfig，怎么也不能生效！
https://www.yuque.com/antv/g6/ggx01g

G6.registerNode('rectAnchor1', {
    getCustomConfig() {
      return {
        default: {
          width: 200,
          radius: 15,
          stroke: '#9254de',
          labelCfg: {
            style: {
              fill: '#9254de',
              fontSize: 12
            }
          },
          linkPoints: {
            top: false,
            right: true,
            bottom: false,
            left: true,
            size: 3,
            fill: '#9254de',
            stroke: '#9254de'
          },
        }
      }
    }
  }, 'rect')

**Comment by eevin** [comment]
https://codesandbox.io/s/ggeditor-flow-tu0p0?file=/src/index.js:0-2538

**Comment by eevin** [comment]
可以了
G6.registerNode('nodeName', {
  options: {
    style: {},
    stateStyles: {
      hover: {},
      selected: {}
    }
  }
}

**Comment by 105197** [comment]
还是不懂
