### ISSUE TITLE
如何禁止重复添加 ID 一样的节点

### ISSUE THREAD

**Issue by Magikarp-2020** [alibaba/GGEditor#512]
codesanbox: https://codesandbox.io/s/ggeditor-flow-rurkj?file=/src/index.js

![image](https://user-images.githubusercontent.com/18202306/82521462-55142680-9b59-11ea-981d-a48c1fb4bd3e.png)

在添加id一样的节点进入画布后，拖拽画布中的元素会以最后添加的元素作为基准。

那么应该如何禁止相同ID的添加呢

> demo code

```jsx

    <GGEditor>
      <ItemPanel className={"itemPanel"}>
        <Item
          className={"item"}
          model={{
            id: "circle",
            type: "circle",
            size: 50,
            label: "circle"
          }}
        >
          <img
            src="https://gw.alicdn.com/tfs/TB1IRuSnRr0gK0jSZFnXXbRRXXa-110-112.png"
            width="55"
            height="56"
            alt=""
            draggable={false}
          />
        </Item>
      </ItemPanel>
      <Flow className={"graph"} data={data} />
    </GGEditor>

```

**Comment by blueju** [comment]
思路：
在将节点拖入画布后~将节点的 model 添加进画布的 model 前，做一层判断，如果画布中已经有相同的元素节点ID了，则中断操作，但问题是，我找了许久，也没发现 ggeditor 有什么中断操作的 api。

因此，当初我是使用抛出错误的方式中断操作的。

下面这些链接，或许对你有帮助：

- https://github.com/blueju/vue-g6-editor/issues/3
- （第382行）https://github.com/blueju/vue-g6-editor/blob/master/src/views/index.vue

虽然以上链接围绕是基于与 ggeditor 的 g6-editor ，但是实现方式应该是相通的。

**Comment by Magikarp-2020** [comment]
@blueju  感谢，由于时间有点久远了已经忘记该问题发生的原因了。

猜测有可能是因为 gg-editor 依赖的 "@antv/g6": "^3.4.3" 更新了所以修复了这个问题

由于无法复现，这个 issues 我关闭掉
