### ISSUE TITLE
请问，现在可以实现Edge的shape为虚线类型吗？有没有自定义shape的方法

### ISSUE THREAD

**Issue by lideyao** [alibaba/GGEditor#514]
## 这个功能解决了什么问题
业务场景多样化

**Comment by HungryBunny-wei** [comment]
和<RegisterNode />一样也有<RegisterEdge />用来自定义线

**Comment by Ynewtime** [comment]
使用 RegisterEdge 注册自定义边即可，虚线可以参考 https://g6.antv.vision/zh/examples/scatter/edge#edge

**Comment by lideyao** [comment]
谢谢大家
