### ISSUE TITLE
为什么新版移除了Toolbar和withPropsApi了呢，有替代方案吗？之前使用2.0.4版本实现的功能都用到了Toolbar和withPropsApi

### ISSUE THREAD

**Issue by 18814127739** [alibaba/GGEditor#521]

**Comment by blueju** [comment]
withPropsAPI 改成了 withEditorContext

**Comment by blueju** [comment]
至于 Toolbar，好像是改使用 Command 需要自己写了，我是这么写的。

https://github.com/blueju/ggeditor/blob/master/src/components/toolbar/index.jsx
