### ISSUE TITLE
拖拽到画布的节点没有只有节点没有四个锚点，但写的死数据有四个锚点

### ISSUE THREAD

**Issue by yz-jaker** [alibaba/GGEditor#524]
import React from 'react'
import GGEditor, { Flow, RegisterNode, setAnchorPointsState, ItemPanel, Item } from 'gg-editor'
import './index.scss'

const data = {
  nodes: [
    {
      id: '0',
      label: 'Node',
      x: 50,
      y: 50,
    },
  ],
  edges: [],
}

function App() {
  return (
    <GGEditor className='editor'>
      <ItemPanel className='item'>
        <Item
          className='item'
          model={{
            type: 'circle',
            size: 50,
            label: 'circle',
          }}
        >
          <img
            src='https://gw.alicdn.com/tfs/TB1IRuSnRr0gK0jSZFnXXbRRXXa-110-112.png'
            width='55'
            height='56'
            draggable={false}
          />
        </Item>
      </ItemPanel>
      <Flow
        className='editorContent'
        data={data}
        graphConfig={{ defaultNode: { type: 'customInternalNode', size: 50 } }}
      />
      <RegisterNode
        name='customInternalNode'
        config={{
          setState(name, value, item) {
            console.log('item', item)
            setAnchorPointsState.call(
              this,
              name,
              value,
              item,
              (item, anchorPoint) => {
                const { width, height } = item.getKeyShape().getBBox()
                const [x, y] = anchorPoint
                return {
                  x: width * x - width / 2,
                  y: height * y - height / 2,
                }
              },
              (item, anchorPoint) => {
                const { width, height } = item.getKeyShape().getBBox()
                const [x, y] = anchorPoint
                return {
                  x: width * x - width / 2,
                  y: height * y - height / 2,
                }
              }
            )
          },
          getAnchorPoints() {
            return [
              [0.5, 0],
              [0.5, 1],
              [0, 0.5],
              [1, 0.5],
            ]
          },
        }}
        extend='circle'
      />
    </GGEditor>
  )
}

export default App

**Comment by yz-jaker** [comment]
@gaoli 力哥，看下，我按照你写的RegisterNode

**Comment by yz-jaker** [comment]
已解决

**Comment by SuperXFan** [comment]
ItemPanel中的元素必须自定义么？ 直接用item没有锚点？

**Comment by mu1004** [comment]
> 已解决

咋解决的啊
