### ISSUE TITLE
关于实现tooltips，能否做下详细说明。

### ISSUE THREAD

**Issue by eevin** [alibaba/GGEditor#549]
版本V2中有个实现Tooltip 的新需求。
翻看了许多Issues ，没找到详细答案，主要是如何获取坐标问题。

#79 有提到使用 getDomPoint 方法获取结点对应 DOM 坐标。在V2中能否实现？能否做详细说明。

自己实现的方式是使用onDragEnd方法获取：domX, domY, x, y。计算画布移动的偏移量结合节点的坐标实现tooltips。
但是发现鼠标滚轮移动会移动画布，无法获取有效的位置。
是否支持滚轮滚动改为缩放。或者禁止滚轮滚动移动图形  #219 ，
而且滚轮移动画布会造成用户在绘制图形的时候误操作，比如绘制图形的初始位置出现在负坐标位置。

**Comment by ShirlyZhang** [comment]
请问您实现了吗，可以贴一下代码看看吗

**Comment by anjamirth** [comment]
@ShirlyZhang @eevin Were you able to solve this? Can you pls guide me.
