### ISSUE TITLE
放大缩小画布BUG

### ISSUE THREAD

**Issue by fx-Aice** [alibaba/GGEditor#570]
## 版本
3.1.3
> 请检查问题是否存在于最新版本中

## 环境

> 系统、浏览器、React 等版本信息
官网中也存在该问题

## 重现链接
流程图中出现，Flow
> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/ggeditor-flow-hq64m) / [Mind](https://codesandbox.io/s/ggeditor-mind-2262q)

## 重现步骤
鼠标放进画布，滑动滚轮会放大或者缩小画布，当画布放大到一定程度，节点显示在画布外面时，缩小画布，此时画布上的节点会消失不见

> 清晰的重现步骤以便迅速定位问题

## 期望的结果是什么
放大缩小画布，不会出现节点消失的情况

**Comment by huangzhongxin** [comment]
将节点移动到画布外面，也会消失

**Comment by huangzhongxin** [comment]
可以看下这个issues，试了下能解决 #507

**Comment by fx-Aice** [comment]
graph.get('canvas').set('localRefresh', false);
