### ISSUE TITLE
editor区域大小发生变化时视口并未随之更新

### ISSUE THREAD

**Issue by NingJing94** [alibaba/GGEditor#590]
## 版本

>3.1.3

## 环境

> chrome

## 重现链接

> https://codesandbox.io/s/ggeditor-flow-hq64m?fontsize=14&hidenavigation=1&theme=dark&file=/src/styles.css

## 重现步骤

> 把右边的Browser窗口拖宽，然后将图拖拽至右边

## 期望的结果是什么
可见区域都能正常显示图的内容

## 实际的结果是什么
会有一块空白盖住图内容，那块空白就是editor的初始区域和resize后最新区域之间的gap
![截屏2021-06-15 下午4 40 24](https://user-images.githubusercontent.com/4077902/122021618-667d4000-cdf8-11eb-9a80-b9b4a25b7a45.png)

**Comment by ljhnhlh** [comment]
请问你解决了吗，我也遇到这个问题

**Comment by NingJing94** [comment]
> 请问你解决了吗，我也遇到这个问题

调一下graph.changeSize就可以了
